  name: Generate Prompt

on:
  push:
    branches: [main]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate prompt file
        run: python scripts/generate_prompt.py

      - name: Commit and Push
        run: |
          git config user.name "crazybird-bot"
          git config user.email "bot@crazybird.system"
          git add output/ena_comfy_prompt.json
          git commit -m "Auto-update: Ena comfy prompt from DNA" || echo "No changes to commit"
          git pull --no-rebase --autostash origin main
          git push origin main

